### ISSUE TITLE
Android Issue

### ISSUE THREAD

**Issue by mmajors** [rhishikeshj/Xamarin.GoogleAuth#2]
Hello,

I have followed your directions multiple times and I cannot figure out what I am receiving this error:

Unable to find explicit activity class {com.openarc.bunxious/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}; have you declared this activity in your AndroidManifest.xml?

The error is occurring in GoogleAuthAndroid on line 79.

Any help would be appreciated.

Great Library!!!

Thanks,
Marc

**Comment by mmajors** [comment]
Found my issue.  My application tag was declared as <Application INSTEAD of <application.

Again, what a great library.

**Comment by rhishikeshj** [comment]
Hi @mmajors, glad that you are finding use for the GoogleAuth plugin 👍 
Regarding the error that you are seeing, I saw the same error when using the latest 42.x.x version of the Google play services components for Xamarin.
Shifting to version 32.961.0 solved the issue for me.
What version are you using in the app ?
